services:
  app:
    build:
      context: .
      # Optionally specify a Dockerfile or buildpack here
      # dockerfile: Dockerfile
      # buildpack: nodejs
    run: npm start
    ports:
      - 3001:3001
    env:
      PORT: 3001
      PLAID_ENV: sandbox
      WEBHOOK_URL: your_webhook_url
      PLAID_SECRET: your_plaid_secret
      ALLOWED_ORIGINS: http://localhost:3000
      PLAID_CLIENT_ID: your_plaid_client_id
